---
- hosts: django_project
  vars:
    db_database: "myproject"
    db_user: "myprojectuser"
    db_password: "password"

  remote_user: root
  roles:
    #- tests
    #- ubuntu-common
    - create-database
    #- flask-webapp
    #- mariadb
    #- { role: geerlingguy.phpmyadmin }
