- name: Update apt-get repo and cache
  apt: 
    update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: "install vim"
  apt:
    name: vim
    state: latest
  when: ansible_pkg_mgr == 'apt'

- name: "install htop"
  apt:
    name: htop
    state: latest
  when: ansible_pkg_mgr == 'apt'

- name: Install a list of packages
  apt:
    pkg:
    - git
    - vim
    - tree
    - nginx
    - make
    - make
    - gcc
    - ntp
    - yamllint
    - unzip
    - sysstat
    - curl 
    - python3
    - ufw
    - python3-pip 
    - python3-dev 
    - build-essential 
    - libssl-dev 
    - libffi-dev 
    - python3-setuptools
    - python3-venv
