---
- hosts: all
  tasks:
    - name: Test connectivity to target server
      hosts: web_server1
      tasks:
        - name: Ping test
          ping:

    - name: System details
      debug: msg="{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_os_family }}"
      - "{{ ansible_distribution_release }}"
