---
- hosts: all
  tasks:
    - name: Get hostname for testing purpose
      command: lsb_release -a
      changed_when: False
      register: hostname
    - debug: var={{ item }}
      with_items:
        - hostname.stdout

    - name: System details
      debug: msg="{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_os_family }}"
      - "{{ ansible_distribution_release }}"
